export const ADD_BUSSINES = 'ADD_BUSSINES'
export const ADD_BUSSINES_GREAT = 'ADD_BUSSINES_GREAT'
export const ADD_BUSSINES_ERROR = 'ADD_BUSSINES_ERROR'


export const START_LOAD_BUSSINES = 'START_LOAD_BUSSINES'
export const LOAD_BUSSINES_GREAT = 'LOAD_BUSSINES_GREAT'
export const LOAD_BUSSINES_ERROR = 'LOAD_BUSSINES_ERROR'


export const GET_BUSSINES_DELETE = 'GET_BUSSINES_DELETE'
export const BUSSINES_DELETE_GREAT = 'BUSSINES_DELETE_GREAT'
export const BUSSINES_DELETE_ERROR = 'BUSSINES_DELETE_ERROR'

export const GET_BUSSINES_EDIT = 'GET_BUSSINES_EDIT'
export const START_BUSSINES_EDIT = 'START_BUSSINES_EDIT'
export const BUSSINES_EDIT_GREAT = 'BUSSINES_EDIT_GREAT'
export const BUSSINES_EDIT_ERROR = 'BUSSINES_EDIT_ERROR'

